name: ukmcl
description: "A Minecraft Launcher for and by the Unknown Group."
publish_to: 'none'
version: 0.0.0-experimental
homepage: https://github.com/TheUnknownGroup/UKMCL

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
