name: Publish to site

on:
  release:
    types: [published]
  push:
    branches:
      - main

  workflow_dispatch:

env:
  ver: 0.0.0-experimental+0-beta.10
  file_ver: 0.0.0

jobs:
  deploy:
    if: ${{ !contains(github.event.head_commit.message, '[site]') }}

    permissions:
      contents: write
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: download files
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir downloads
          cd downloads
          
          gh release download --repo TheUnknownGroup/UKMCL ${{ env.ver }} --pattern "UKMCL-Windows-Installer-en_US.exe"
          gh release download --repo TheUnknownGroup/UKMCL ${{ env.ver }} --pattern "UKMCL-macOS-en_US+${{ env.file_ver }}.dmg"
          gh release download --repo TheUnknownGroup/UKMCL ${{ env.ver }} --pattern "UKMCL-Linux-Installer-en_US+${{ env.file_ver }}.deb"

      - name: copy
        run: |
          mkdir output
          cp downloads/*.exe output/
          cp downloads/*.deb output/
          cp downloads/*.dmg output/

      - name: clone repo
        run: |
          git clone https://github.com/TheUnknownGroup/theunknowngroup.github.io.git repo
          cd repo/src/pages/
          mkdir out
          mkdir launcher
          cd ${{ github.workspace }}
          cp output/*.exe repo/src/pages/out/
          cp output/*.deb repo/src/pages/out/
          cp output/*.dmg repo/src/pages/out/

      - name: make version-lin.json
        run: |
          echo '{ "version": "${{ env.ver }}", "changelog": "https://github.com/TheUnknownGroup/UKMCL/blob/main/changelog.md", "download_url": "https://web.thegremlinx.xyz/out/UKMCL-Linux-Installer-en_US+${{ env.file_ver }}.deb"' > version-lin.json
          cp version-lin.json repo/src/pages/launcher

      - name: make version-win.json
        run: |
          echo '{ "version": "${{ env.ver }}", "changelog": "https://github.com/TheUnknownGroup/UKMCL/blob/main/changelog.md", "download_url": "https://web.thegremlinx.xyz/out/UKMCL-Windows-Installer-en_US.exe"' > version-win.json
          cp version-win.json repo/src/pages/launcher      

      - name: make version-mac.json
        run: |
          echo '{ "version": "${{ env.ver }}", "changelog": "https://github.com/TheUnknownGroup/UKMCL/blob/main/changelog.md", "download_url": "https://web.thegremlinx.xyz/out/UKMCL-macOS-en_US+${{ env.file_ver }}.dmg"' > version-mac.json
          cp version-mac.json repo/src/pages/launcher
          
      - name: test upload
        uses: actions/upload-artifact@v4
        with:
          name: test
          path: repo/src/pages/launcher