name: Deploy to Website

on:
  release:
    types: [published]
# testing purposes only
  push:
    branches:
      - main
  workflow_dispatch:

env:
  file_ver: 0.0.0
  ver: 0.0.0-experimental+0-beta.10
  ver_tag: 0.0.0-experimental%2B0-beta.10
  commit_msg: update
  url: https://github.com/TheUnknownGroup/UKMCL/releases/download/

jobs:
  deploy:
    if: ${{ !contains(github.event.head_commit.message, '[site]') }}

    permissions:
      contents: write
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: copy
        run: |
          git clone https://x-access-token:${{ secrets.WEBSITE_TOKEN }}@github.com/TheUnknownGroup/theunknowngroup.github.io.git repo
          cd repo/public/

          if [ -d "launcher" ]; then
            echo "Exists"
          else
            mkdir -p launcher
          fi
          
          cd ${{ github.workspace }}
          
      - name: manual add
        if: ${{ contains(github.event.head_commit.message, '[man]') }}
        run:
          mv json/tmp-lin.json json/version-lin.json
          mv json/tmp-win.json json/version-win.json
          mv json/tmp-mac.json json/version-mac.json
          cp json/version-lin.json repo/public/launcher/
          cp json/version-win.json repo/public/launcher/
          cp json/version-mac.json repo/public/launcher/

      - name: get jq
        if: ${{ contains(github.event.head_commit.message, '[newver]') }}
        run: |
          sudo apt-get update
          sudo apt-get install jq

      - name: new ver-lin
        if: ${{ contains(github.event.head_commit.message, '[newver]') }}
        run: |
          jq --arg version "${{ env.ver }}" \
             --arg changelog "https://github.com/TheUnknownGroup/UKMCL/releases/tag/${{ env.ver_tag }}" \
             --arg url "${{ env.url }}${{ env.ver_tag }}/UKMCL-Linux-Installer-en_US+${{ env.file_ver }}.deb" \
             '.versions += [
            {
              "version": $version,
              "changelog": $changelog,
              "download_url": $url
            }
          ]' json/tmp-lin.json > json/version-lin.json
          cp json/version-lin.json repo/public/launcher/

      - name: new ver-win
        if: ${{ contains(github.event.head_commit.message, '[newver]') }}
        run: |
          jq --arg version "${{ env.ver }}" \
             --arg changelog "https://github.com/TheUnknownGroup/UKMCL/releases/tag/${{ env.ver_tag }}" \
             --arg url "${{ env.url }}${{ env.ver_tag }}/UKMCL-Windows-Installer-en_US.exe" \
             '.versions += [
            {
              "version": $version,
              "changelog": $changelog,
              "download_url": $url
            }
          ]' json/tmp-win.json > json/version-win.json
          cp json/version-win.json repo/public/launcher/

      - name: new ver-mac
        if: ${{ contains(github.event.head_commit.message, '[newver]') }}
        run: |
          jq --arg version "${{ env.ver }}" \
             --arg changelog "https://github.com/TheUnknownGroup/UKMCL/releases/tag/${{ env.ver_tag }}" \
             --arg url "${{ env.url }}${{ env.ver_tag }}/UKMCL-macOS-en_US+${{ env.file_ver }}.dmg" \
             '.versions += [
            {
              "version": $version,
              "changelog": $changelog,
              "download_url": $url
            }
          ]' json/tmp-mac.json > json/version-mac.json
          cp json/version-mac.json repo/public/launcher/

      - name: push to website
        run: |
          cd repo/
          git config user.name "devonk15"
          git config user.email "94760159+devonk15@users.noreply.github.com"
          git add public/launcher/*.json

          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "${{ env.commit_msg }}"
            git push
          fi

      - name: push here
        if: ${{ contains(github.event.head_commit.message, '[newver]') }}
        run: |
          mv json/version-lin.json json/tmp-lin.json
          mv json/version-win.json json/tmp-win.json
          mv json/version-mac.json json/tmp-mac.json
          
          git config user.name "devonk15"
          git config user.email "94760159+devonk15@users.noreply.github.com"
          git add json/*.json
          git commit -m "${{ env.commit_msg }}"
          git push