name: Publish to site

on:
  release:
    types: [published]
  push:
    branches:
      - main

  workflow_dispatch:

env:
  ver: 0.0.0-experimental+0-beta.10
  file_ver: 0.0.0

jobs:
  deploy:
    if: ${{ !contains(github.event.head_commit.message, '[site]') }}

    permissions:
      contents: write
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: download files
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir downloads
          cd downloads
          
          gh release download --repo TheUnknownGroup/UKMCL ${{ env.ver }} --pattern "UKMCL-Windows-Installer-en_US.exe"
          gh release download --repo TheUnknownGroup/UKMCL ${{ env.ver }} --pattern "UKMCL-macOS-en_US+${{ env.file_ver }}.dmg"
          gh release download --repo TheUnknownGroup/UKMCL ${{ env.ver }} --pattern "UKMCL-Linux-Installer-en_US+${{ env.file_ver }}.deb"

      - name: copy
        run: |
          mkdir out
          cp downloads/*.exe out/
          cp downloads/*.deb out/
          cp downloads/*.dmg out/
          git clone https://github.com/TheUnknownGroup/theunknowngroup.github.io.git repo
          cd repo/src/pages/
          mkdir out
          mkdir launcher
          cd ${{ github.workspace }}
          cp out/ repo/src/pages/out/
          
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: test
          path: out/
          retention-days: 1
#          echo '{ "version": "${{ env.ver }}", "changelog": "https://github.com/TheUnknownGroup/UKMCL/blob/main/changelog.md", "download_url": "https://web.thegremlinx.xyz/out/UKMCL-Linux-Installer-en_US+${{ env.file_ver }}.deb"' > version-lin.json
#          cp version-lin.json repo/src/pages/launcher