name: Publish to site

on:
  release:
    types: [published]
  push:
    branches:
      - main
  workflow_dispatch:

env:
  ver: 0.0.0-experimental+0-beta.10
  ver_tag: 0.0.0-experimental%2B0-beta.10
  file_ver: 0.0.0
  commit_msg: set [skip]

jobs:
  deploy:
    if: ${{ !contains(github.event.head_commit.message, '[n-site]') }}

    permissions:
      contents: write
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: download files
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir downloads
          cd downloads
          
          gh release download --repo TheUnknownGroup/UKMCL ${{ env.ver }} --pattern "UKMCL-Windows-Installer-en_US.exe"
          gh release download --repo TheUnknownGroup/UKMCL ${{ env.ver }} --pattern "UKMCL-macOS-en_US+${{ env.file_ver }}.dmg"
          gh release download --repo TheUnknownGroup/UKMCL ${{ env.ver }} --pattern "UKMCL-Linux-Installer-en_US+${{ env.file_ver }}.deb"

      - name: copy
        run: |
          git clone https://x-access-token:${{ secrets.WEBSITE_TOKEN }}@github.com/TheUnknownGroup/theunknowngroup.github.io.git repo
          cd repo/
          mkdir out
          mkdir launcher
          cd ${{ github.workspace }}
          cp downloads/*.exe repo/out/
          cp downloads/*.deb repo/out/
          cp downloads/*.dmg repo/out/

      - name: make version-lin.json
        run: |
          echo '{ 
              "versions": [ 
              { 
                "version": "${{ env.ver }}", 
                "changelog": "https://github.com/TheUnknownGroup/UKMCL/releases/tag/${{ env.ver_tag }}", 
                "download_url": "https://web.thegremlinx.xyz/out/UKMCL-Linux-Installer-en_US+${{ env.file_ver }}.deb" } 
              ] 
          }' > version-lin.json
          cp version-lin.json repo/launcher/

      - name: make version-win.json
        run: |
          echo '{ 
              "versions": [ 
              { 
                "version": "${{ env.ver }}", 
                "changelog": "https://github.com/TheUnknownGroup/UKMCL/releases/tag/${{ env.ver_tag }}", 
                "download_url": "https://web.thegremlinx.xyz/out/UKMCL-Windows-Installer-en_US.exe" } 
              ] 
          }' > version-win.json
          cp version-win.json repo/launcher/

      - name: make version-mac.json
        run: |
          echo '{ 
              "versions": [ 
              { 
                "version": "${{ env.ver }}", 
                "changelog": "https://github.com/TheUnknownGroup/UKMCL/releases/tag/${{ env.ver_tag }}", 
                "download_url": "https://web.thegremlinx.xyz/out/UKMCL-macOS-en_US+${{ env.file_ver }}.dmg" } 
              ] 
          }' > version-mac.json
          cp version-mac.json repo/launcher/

      - name: push to repo
        run: |
          cd repo
          git config user.name "devonk15"
          git config user.email "94760159+devonk15@users.noreply.github.com"
          git add out/UKMCL-Windows-Installer-en_US.exe
          git add out/UKMCL-macOS-en_US+${{ env.file_ver }}.dmg
          git add out/UKMCL-Linux-Installer-en_US+${{ env.file_ver }}.deb
          git add launcher/*.json
          git commit -m "${{ env.commit_msg }}"
          git push